version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - data_db:/var/lib/mysql
    restart: always
    ports:
      - 33306:3306
    networks:
      phplist:
        ipv4_address: 172.25.0.102
    env_file:
      - build/docker-stack.env

  postgresql:
    restart: always
    volumes:
      - data_postgres_db:/var/lib/postgresql/data
    networks:
      phplist:
        ipv4_address: 172.25.0.103
    ports:
      - 55432:5432
    env_file:
      - build/docker-stack.env
    build:
      context: .
      dockerfile: build/Dockerfile-postgresql
  
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
    networks:
      phplist:

  cache:
    image: memcached
    restart: always
    networks:
      phplist:

  phplist:
    depends_on:
      - mysql
      - mailhog
      - cache
    image: phplist-caixa
    restart: always
    volumes:
      - ./:/var/www/phplist:rw
    networks:
      phplist:
        ipv4_address: 172.25.0.101
    env_file:
      - build/docker-stack.env
    entrypoint:
      - build/dev-init.sh

  migration:
    depends_on:
      - mysql
    image: phplist-caixa
    volumes:
      - ./:/var/www/phplist:rw
    networks:
      phplist:
    env_file:
      - build/docker-stack.env
    entrypoint:
      - build/migration-init.sh

volumes:
  data_db:
  data_postgres_db:

networks:
  phplist:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24